<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>SimpleLedger</RootNamespace>
    <AssemblyName>SimpleLedger</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LedgerModel\LedgerModel.csproj" />
  </ItemGroup>

</Project>
